### ISSUE TITLE
Sur formulaire de création et d'édition, suppression du blos débugage des données dans template

### ISSUE THREAD

**Issue by Chrispnv** [PnVanoise/cables#116]

**Comment by xaadim** [comment]
Tu peux mettre le debug à false dans app.js 
https://github.com/PnVanoise/cables/blob/master/web/js/app.js#L105

**Comment by ClaireLagaye** [comment]
ok je m'en occupe !

Le 30/12/2015 10:43, Khadim Mbacké a écrit :
>
> Tu peux mettre le debug à false dans app.js
> https://github.com/PnVanoise/cables/blob/master/web/js/app.js#L105
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/PnVanoise/cables/issues/116#issuecomment-167968216>.
>

--
