### ISSUE TITLE
Mortalités : Filtre sur colonne ID ne fonctionne pas

### ISSUE THREAD

**Issue by Chrispnv** [PnVanoise/cables#122]
Vérification sur toutes les autres données métier. Bug uniquement sur les mortalités

**Comment by xaadim** [comment]
remplacer id_cas_mortalite par id : https://github.com/PnVanoise/cables/blob/master/src/PNV/CablesBundle/Resources/clientConf/TCasMortalite/list.yml#L12 @Chrispnv

**Comment by Chrispnv** [comment]
Corrigé avec commit #122
