### ISSUE TITLE
Quand on supprime un objet (depuis son détail), recharger la couche

### ISSUE THREAD

**Issue by ClaireLagaye** [PnVanoise/cables#137]

**Comment by xaadim** [comment]
Je pense que c'est lié à tes triggers @ClaireLagaye. Sinon essaie de recharger la carte avec forceLoad.

**Comment by Chrispnv** [comment]
Salut Khadim,
comment vas tu ? Tout se passe bien au Sénégal, le soleil, la famille...
Tu vas être content de revenir, ici il pleut, il pleut, il pleut, il fait gris,il fait gris, il fait gris...

Ce n'est pas un problème de triggers, c'est simplement de faire un forcereload sur les zones sensibles

**Comment by xaadim** [comment]
Salut,

Ah les Sénégal il fait chaud mais ça va on survit (histoire d'habitude).
J'espère que l'appli avance bien.

Le mardi 12 janvier 2016, CHILLET Christophe <notifications@github.com> a
écrit :

> Salut Khadim,
> comment vas tu ? Tout se passe bien au Sénégal, le soleil, la famille...
> Tu vas être content de revenir, ici il pleut, il pleut, il pleut, il fait
> gris,il fait gris, il fait gris...
>
> Ce n'est pas un problème de triggers, c'est simplement de faire un
> forcereload sur les zones sensibles
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PnVanoise/cables/issues/137#issuecomment-170817558>.
>


-- 

[image: Khadim Dev] <http://www.khadimdev.com/>

Khadim Mbacké

+33  6 38 22 64 17

contact@khadimdev.com - http://khadimdev.com/

 [image: Linkedin] <http://fr.linkedin.com/pub/khadim-mbacke/61/4ba/b15>

**Comment by Chrispnv** [comment]
Comme pour issue #136 dataServ.forceReload = true; oté dans les controleurs
