### ISSUE TITLE
Retour page détail depuis édition sans enregistrement : l'élément sélectionné sur la carte n'est plus en rouge

### ISSUE THREAD

**Issue by Chrispnv** [PnVanoise/cables#152]
Edition objet > clic sur 2e partie breadcrumb pour revenir sur page détail de l'objet
=> l'objet dans la carte n'est plus sélectionné en rouge

**Comment by xaadim** [comment]
Salut,  
J'ai une connexion pas très rapide, j'ai l'impression que la carte se recharge à chaque fois qu'on passe en détail et en édition.

**Comment by Chrispnv** [comment]
Commit #169
