### ISSUE TITLE
Dans detail poteau, mettre le type de poteau en label

### ISSUE THREAD

**Issue by ClaireLagaye** [PnVanoise/cables#8]

**Comment by xaadim** [comment]
Corrigé : https://github.com/PnVanoise/cables/commit/1accece3b8d5f8c3f7fb551a75a02c08c9d2bce0

**Comment by ClaireLagaye** [comment]
trop fort !

Le 10/12/2015 16:04, Khadim Mbacké a écrit :
>
> Closed #8 <https://github.com/PnVanoise/cables/issues/8>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/PnVanoise/cables/issues/8#event-488276195>.
>

--
